### Import dependencies and load the data file

In [1]:
import pandas as pd
import numpy as np
import datetime as dt
import json

In [ ]:
#movies_file = "Resources_new/movies.csv"
#movies_df = pd.read_csv(movies_file)
#movies_df.head(5)

In [3]:
cancer_types_file = "data/total-cancer-deaths-by-type.csv"
cancertypes_df = pd.read_csv(cancer_types_file)
cancertypes_df.head(5)

,Entity,Code,Year,Deaths - Liver cancer - Sex: Both - Age: All Ages (Number),Deaths - Kidney cancer - Sex: Both - Age: All Ages (Number),Deaths - Larynx cancer - Sex: Both - Age: All Ages (Number),Deaths - Breast cancer - Sex: Both - Age: All Ages (Number),Deaths - Thyroid cancer - Sex: Both - Age: All Ages (Number),Deaths - Stomach cancer - Sex: Both - Age: All Ages (Number),Deaths - Bladder cancer - Sex: Both - Age: All Ages (Number),...,Deaths - Lip and oral cavity cancer - Sex: Both - Age: All Ages (Number),Deaths - Brain and nervous system cancer - Sex: Both - Age: All Ages (Number),"Deaths - Tracheal, bronchus, and lung cancer - Sex: Both - Age: All Ages (Number)",Deaths - Gallbladder and biliary tract cancer - Sex: Both - Age: All Ages (Number),Deaths - Malignant skin melanoma - Sex: Both - Age: All Ages (Number),Deaths - Leukemia - Sex: Both - Age: All Ages (Number),Deaths - Hodgkin lymphoma - Sex: Both - Age: All Ages (Number),Deaths - Multiple myeloma - Sex: Both - Age: All Ages (Number),Deaths - Other neoplasms - Sex: Both - Age: All Ages (Number),Non-Hodgkin lymphoma (deaths)
0,Afghanistan,AFG,1990,466.253436,80.073955,290.099710,566.064939,55.237646,2539.307228,215.632714,...,94.797076,436.803024,956.571414,158.643663,38.136505,755.346768,148.044214,73.421959,14.700016,172.0
1,Afghanistan,AFG,1991,464.137333,79.617930,293.578079,569.733770,55.733210,2578.463804,218.264694,...,96.200684,440.421855,957.902832,160.305013,38.851810,766.950668,151.982681,74.062465,14.942015,183.0
2,Afghanistan,AFG,1992,471.634765,81.300485,303.083772,596.596603,58.219683,2681.232717,223.783862,...,99.492049,473.142029,971.879501,164.741624,40.982141,826.257248,168.151360,75.965459,15.704282,197.0
3,Afghanistan,AFG,1993,480.629105,84.770448,314.296364,626.891389,61.200264,2804.991395,230.028721,...,103.130549,524.190466,986.257891,169.337997,43.499451,915.423760,188.783361,77.835488,16.748916,215.0
4,Afghanistan,AFG,1994,482.489934,87.711539,322.791026,642.000188,62.795340,2904.039548,234.441256,...,105.411865,562.052598,992.539360,172.063135,44.983330,973.560759,199.535545,78.774421,17.406808,232.0

In [4]:
risk_factors_file = "data/share-of-cancer-deaths-attributed-to-risk-factors.csv"
riskfactors_df = pd.read_csv(risk_factors_file)
riskfactors_df.head(5)

,Entity,Code,Year,Share of deaths attributable to risk factors
0,Adverse effects of medical treatment,NaN,2016,0.0
1,African trypanosomiasis,NaN,2016,0.0
2,Alzheimer disease and other dementias,NaN,2016,21.4
3,Aortic aneurysm,NaN,2016,44.2
4,Asthma,NaN,2016,32.3

In [6]:
cancer_pop_age_file = "data/share-of-population-with-cancer-by-age.csv"
cancerbyage_df = pd.read_csv(cancer_pop_age_file)
cancerbyage_df.head(5)

,Entity,Code,Year,Prevalence - Neoplasms - Sex: Both - Age: Under 5 (Percent),Prevalence - Neoplasms - Sex: Both - Age: 70+ years (Percent),Prevalence - Neoplasms - Sex: Both - Age: 15-49 years (Percent),Prevalence - Neoplasms - Sex: Both - Age: 50-69 years (Percent),Prevalence - Neoplasms - Sex: Both - Age: 5-14 years (Percent),Prevalence - Neoplasms - Sex: Both - Age: All Ages (Percent)
0,Afghanistan,AFG,1990,0.218791,1.715018,0.275733,1.139524,0.082218,0.377740
1,Afghanistan,AFG,1991,0.200244,1.718245,0.264010,1.149097,0.082399,0.367866
2,Afghanistan,AFG,1992,0.165107,1.725814,0.241485,1.161123,0.079459,0.332801
3,Afghanistan,AFG,1993,0.155177,1.740286,0.222499,1.174746,0.081895,0.307616
4,Afghanistan,AFG,1994,0.163521,1.749073,0.220448,1.192854,0.082420,0.305005

In [7]:
cancer_pop_type_file = "data/share-of-population-with-cancer-types.csv"
cancerbytypes_df = pd.read_csv(cancer_pop_type_file)
cancerbytypes_df.head(5)

FileNotFoundError: [Errno 2] No such file or directory: 'data/share-of-population-with-cancer-by-types.csv'